"use client";

import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import Image from "next/image";
import Title from "@/components/common/title";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { LastUpdated } from "@/components/common/last-updated";

const logos: { [key: string]: string } = {
  pmPortal: "/Partner logo/SciLifeLab_Logotype_Green_POS.png",
  tefHealth: "/Partner logo/tefhealth_logo.png",
  brainchild: "/Partner logo/Barncancerfonden.png",
  tehdas2: "/Partner logo/tehdas2_logo.png",
};

interface Project {
  name: string;
  description: string;
  url: string;
  logoKey?: string; // Reference to logos object
}

const projects: Project[] = [
  {
    name: "SciLifeLab Precision Medicine (PM) Portal",
    description:
      "The PM Portal is a new service for researchers in the precision medicine field, designed to support and accelerate data-driven life science research in Sweden. It provides links to various data sources, customised dashboards, and resources for navigating data management challenges. Researchers can also find guidance on handling sensitive data and links to relevant tools and services.\n\nThe portal aims to promote open science by helping research groups make their data FAIR and publicly accessible. The portal is part of the SciLifeLab Data Platform, operated by the SciLifeLab Data Centre.",
    url: "https://precision-medicine-portal.scilifelab.se",
    logoKey: "pmPortal",
  },
  {
    name: "The Karolinska Institutet Adaptive Immune Receptor Gene Variant Atlas (KIARVA)",
    description:
      "KIARVA is an open-source immunology database of all gene variants coding for B and T cell receptors. How the receptors are affected by different gene variants is shown by individual immune responses to e.g. vaccines, medicines, and infections, and is also a possible explanation for autoimmune diseases.\n\nKIARVA currently includes 479 IGHV, 10 IGHJ, and 40 IGHD alleles, with frequency data across 5 superpopulations and 25 subpopulations. It provides downloadable FASTA files and supports the study of IG variation at individual and population levels. The data was generated by Gunilla Karlsson Hedestam’s research group at Karolinska Institutet, while the service was developed and integrated into the Precision Medicine Portal by the Data Science Node in Precision Medicine and Diagnostics (DSN-PMD).",
    url: "https://kiarva.scilifelab.se",
  },
  {
    name: "PM Sample Central",
    description:
      "This project is part of the Personalised Cancer Medicine Program at KI, aiming to improve the use of cancer patient samples for advanced profiling to enhance precision medicine. It addresses challenges in sample handling, data integration, and stakeholder coordination while ensuring high-quality preparation and data integrity. The DSN-PMD drives Work Package 2, with the key goal of developing unique sample ID and pseudonymisation tools to track samples and safeguard patient data. Funded by Radiumhemmet.",
    url: "https://ki.se/en/cancer-research-ki/research/personalised-cancer-medicine-pcm-program",
  },
  {
    name: "RAGnar",
    description:
      "RAGnar is a retrieval-augmented generation (RAG) AI tool aiming to support researchers and students in the field of precision medicine. It combines the capabilities of large language models with the ability to retrieve relevant information from external knowledge sources, ensuring that responses are accurate and well-grounded in reliable data.\n\nCurrently, RAGnar leverages open-access publications and abstracts from PubMed, referencing any paper it bases its answers on. This approach enhances transparency and credibility, making it a valuable resource for exploring precision medicine topics. RAGnar will be launched as a standalone page and will also be prominently featured on the Precision Medicine Portal.",
    url: "https://precision-medicine-portal.scilifelab.se",
  },
  {
    name: "TEF-Health",
    description:
      "The European Commission co-funded TEF-Health, one of four Testing and Experimentation Facilities (TEFs) established by the EU to support innovation in artificial intelligence and robotics. TEF-Health focuses on providing expertise and assistance to small and medium-sized enterprises (SMEs) and innovators working in the health sector. The main goal is to boost implementation of AI-driven solutions into healthcare by providing services and tools for validation and certification of the latest technology while ensuring compliance with relevant legal, ethical, quality, and interoperability standards and requirements.\n\nThe DSN-PMD is strongly involved in Work Package 4, which manages all the virtual testing services developed and provided. Apart from working on the services, the Data Science Node is also active in general activities and took leadership in the development of the Curation Tool, an application to streamline and simplify change management for the overall service catalogue.",
    url: "https://tefhealth.eu/home",
    logoKey: "tefHealth",
  },
  {
    name: "Towards European health data space 2nd joint action (TEHDAS2)",
    description:
      "The EU regulation on the European health data space (EHDS) came into force in March 2025, and will be fully implemented in 2031. EHDS primary use of health data enables individuals to securely share their electronic health data with healthcare providers across member states. EHDS secondary use of health data aims to facilitate the use of health data for research, innovation, policymaking, and public health, while ensuring strong data protection.\n\nThe TEHDAS2 project will develop guidelines and technical specifications to ensure a harmonized implementation of the EHDS regulation with a specific focus on secondary use of health data.\n\nThe DSN-PMD is involved in two of the work packages (WP). In WP 5 'Data discovery – finding and exposing metadata' we are involved in developing guidance on enrichment of datasets. In WP 7 'Safe and secure processing' we are contributing to the documentation on secure processing environments.",
    url: "https://tehdas.eu/",
    logoKey: "tehdas2",
  },
  {
    name: "Trusted Research Environment (TRE) exploration",
    description:
      "Trusted Research Environments, also called Secure Processing Environments, are secure, controlled computing platforms designed to enable authorized researchers from approved institutions to remotely access, store, and analyze sensitive data in a protected manner.\n\nThe DSN-PMD led a pre-study for the Data Centre, conducting an initial evaluation of suitable providers, interviewing SciLifeLab platforms and facilities, and creating recommendations for future work and projects. Apart from SciLifeLab-specific studies, leadership was also taken for regional, national, and European initiatives. This includes creating and guiding a TRE-specific working group within the TEF-Health project. Finally, the Data Science Node also participated in relevant conferences and regional and national discussions.",
    url: "https://tefhealth.eu/home",
  },
  {
    name: "BrainChild (previous involvement)",
    description:
      "The BrainChild project, led by the Swedish Childhood Cancer Fund, aims to create a centralised data platform for securely collecting, storing, analysing, and sharing childhood cancer data, integrating AI to enhance research and healthcare. By addressing data fragmentation, BrainChild strives to improve treatment outcomes and advance childhood cancer care.\n\nThe DSN-PMD participated in the Technical Design & Architecture working group during the pilot project.",
    logoKey: "brainchild",
    url: "https://www.barncancerfonden.se/press/2024/regeringen-finansierar-brainchild-med-10-miljoner-kronor/",
  },
];

export default function AboutDSNPMDProjectsPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <nav aria-label="Breadcrumb navigation" role="navigation">
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Home</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/about">About us</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/about/dsnpmd-projects">
                DSN-PMD Projects
              </BreadcrumbLink>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      </nav>

      <Title level={2} className="mb-10">
        Projects of the Data Science Node in Precision Medicine and Diagnostics
      </Title>

      <section aria-label="DSN-PMD Projects" className="mb-8">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6" role="list">
          {projects.map((project, index) => (
            <article key={index} role="listitem" className="h-full">
              <Card className="shadow-md h-full flex flex-col">
                <CardHeader className="bg-muted flex flex-row items-center justify-between p-4 h-auto lg:h-20">
                  <div className="flex-1 text-left">
                    <CardTitle className="text-lg">
                      <a
                        href={project.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-primary hover:underline focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 rounded"
                        aria-label={`Visit ${project.name} website (opens in new tab)`}
                      >
                        {project.name}
                      </a>
                    </CardTitle>
                  </div>

                  {project.logoKey && logos[project.logoKey] && (
                    <div className="flex-shrink-0" aria-hidden="true">
                      <Image
                        src={logos[project.logoKey]}
                        alt=""
                        width={128}
                        height={64}
                        className="object-contain max-h-[64px]"
                        role="presentation"
                      />
                    </div>
                  )}
                </CardHeader>
                <CardContent className="p-4 flex-1">
                  <p className="whitespace-pre-line">{project.description}</p>
                </CardContent>
              </Card>
            </article>
          ))}
        </div>
      </section>

      <div className="mt-8">
        <LastUpdated date="21-05-2025" />
      </div>
    </div>
  );
}
