"use client";

import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import Image from "next/image";
import Title from "@/components/common/title";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { LastUpdated } from "@/components/common/last-updated";
import { TrackPageViewIfEnabled } from "@/util/cookiesHandling";

const logos: { [key: string]: string } = {
  pmPortal: "/Partner logo/SciLifeLab_Logotype_Green_POS.png",
  tefHealth: "/Partner logo/tefhealth_logo.png",
  brainchild: "/Partner logo/Barncancerfonden.png",
};

interface Project {
  name: string;
  description: string;
  url: string;
  logoKey?: string; // Reference to logos object
}

const projects: Project[] = [
  {
    name: "SciLifeLab Precision Medicine (PM) Portal",
    description:
      "The PM Portal is a new service for researchers in the precision medicine field, designed to support and accelerate data-driven life science research in Sweden. It provides links to various data sources, customised dashboards, and resources for navigating data management challenges. Researchers can also find guidance on handling sensitive data and links to relevant tools and services.\n\nThe portal aims to promote open science by helping research groups make their data FAIR and publicly accessible. The portal is part of the SciLifeLab Data Platform, operated by the SciLifeLab Data Centre.",
    url: "https://precision-medicine-portal.scilifelab.se",
    logoKey: "pmPortal",
  },
  {
    name: "The Karolinska Institutet Adaptive Immune Receptor Gene Variant Atlas (KIARVA)",
    description:
      "KIARVA is an open-source immunology database of all gene variants coding for B and T cell receptors. How the receptors are affected by different gene variants is shown by individual immune responses to e.g. vaccines, medicines, and infections, and is also a possible explanation for autoimmune diseases.\n\nKIARVA currently includes 479 IGHV, 10 IGHJ, and 40 IGHD alleles, with frequency data across 5 superpopulations and 25 subpopulations. It provides downloadable FASTA files and supports the study of IG variation at individual and population levels. The data was generated by Gunilla Karlsson Hedestam’s research group at Karolinska Institutet, while the service was developed and integrated into the Precision Medicine Portal by the Data Science Node in Precision Medicine and Diagnostics (DSN-PMD).",
    url: "https://kiarva.scilifelab.se",
  },
  {
    name: "PM Sample Central",
    description:
      "This project is part of the Personalised Cancer Medicine Program at KI, aiming to improve the use of cancer patient samples for advanced profiling to enhance precision medicine. It addresses challenges in sample handling, data integration, and stakeholder coordination while ensuring high-quality preparation and data integrity. The DSN-PMD drives Work Package 2, with the key goal of developing unique sample ID and pseudonymisation tools to track samples and safeguard patient data. Funded by Radiumhemmet.",
    url: "https://ki.se/en/cancer-research-ki/research/personalised-cancer-medicine-pcm-program",
  },
  {
    name: "RAGnar",
    description:
      "RAGnar is a retrieval-augmented generation (RAG) AI tool aiming to support researchers and students in the field of precision medicine. It combines the capabilities of large language models with the ability to retrieve relevant information from external knowledge sources, ensuring that responses are accurate and well-grounded in reliable data.\n\nCurrently, RAGnar leverages open-access publications and abstracts from PubMed, referencing any paper it bases its answers on. This approach enhances transparency and credibility, making it a valuable resource for exploring precision medicine topics. RAGnar will be launched as a standalone page and will also be prominently featured on the Precision Medicine Portal.",
    url: "https://precision-medicine-portal.scilifelab.se",
  },
  {
    name: "TEF-Health",
    description:
      "The European Commission co-funded TEF-Health, a major EU project providing expertise and assistance to small and medium-sized enterprises and innovators. The main goal is to boost implementation of AI-driven solutions into healthcare by providing services and tools for validation and certification of the latest technology while ensuring compliance with relevant legal, ethical, quality, and interoperability standards and requirements.\n\nThe DSN-PMD is strongly involved in Work Package 4, which manages all the virtual testing services developed and provided. Apart from working on the services, the Data Science Node is also active in general activities and took leadership in the development of the Curation Tool, an application to streamline and simplify change management for the overall service catalogue.",
    url: "https://tefhealth.eu/home",
    logoKey: "tefHealth",
  },
  {
    name: "Trusted Research Environment (TRE) exploration",
    description:
      "Trusted Research Environments, also called Secure Processing Environments, are secure, controlled computing platforms designed to enable authorized researchers from approved institutions to remotely access, store, and analyze sensitive data in a protected manner.\n\nThe DSN-PMD led a pre-study for the Data Centre, conducting an initial evaluation of suitable providers, interviewing SciLifeLab platforms and facilities, and creating recommendations for future work and projects. Apart from SciLifeLab-specific studies, leadership was also taken for regional, national, and European initiatives. This includes creating and guiding a TRE-specific working group within the TEF-Health project and contributing to Work Package 7.4 in TEHDAS2, a project that supports the development and implementation of the European Health Data Space. Finally, the Data Science Node also participated in relevant conferences and regional and national discussions.",
    url: "https://tehdas.eu",
  },
  {
    name: "BrainChild (previous involvement)",
    description:
      "The BrainChild project, led by the Swedish Childhood Cancer Fund, aims to create a centralised data platform for securely collecting, storing, analysing, and sharing childhood cancer data, integrating AI to enhance research and healthcare. By addressing data fragmentation, BrainChild strives to improve treatment outcomes and advance childhood cancer care.\n\nThe DSN-PMD participated in the Technical Design & Architecture working group during the pilot project.",
    logoKey: "brainchild",
    url: "https://www.barncancerfonden.se/press/2024/regeringen-finansierar-brainchild-med-10-miljoner-kronor/",
  },
];

export default function DSNProjectsPage() {
  TrackPageViewIfEnabled();

  return (
    <div className="container mx-auto px-4 py-8">
      <Breadcrumb>
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/">Home</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbLink href="/about">About us</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbLink href="/about/dsnpmd-projects">
              DSN-PMD Projects
            </BreadcrumbLink>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      <Title level={2}>
        Projects of the Data Science Node in Precision Medicine and Diagnostics
      </Title>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {projects.map((project, index) => (
          <Card key={index} className="shadow-md">
            <CardHeader className="bg-muted flex flex-row items-center justify-between p-4 h-auto lg:h-20">
              {/* Left-aligned title */}
              <div className="flex-1 text-left">
                <CardTitle className="text-lg">
                  <a
                    href={project.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary hover:underline"
                  >
                    {project.name}
                  </a>
                </CardTitle>
              </div>

              {/* Right-aligned logo (consistent size) */}
              {project.logoKey && logos[project.logoKey] && (
                <div className="flex-shrink-0">
                  <Image
                    src={logos[project.logoKey]}
                    alt={project.name}
                    width={128} // Standardized width
                    height={64} // Standardized height
                    className="object-contain"
                  />
                </div>
              )}
            </CardHeader>
            <CardContent className="p-4">
              <p className="whitespace-pre-line">{project.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>
      <LastUpdated date="11-03-2025" />
    </div>
  );
}
